<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../CodeMuster.Domain/CodeMuster.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CodeMuster.Infrastructure.Tests" />
  </ItemGroup>
</Project>
