<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="prices.json" LogicalName="CodeMuster.Application.prices.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CodeMuster.Domain/CodeMuster.Domain.csproj" />
  </ItemGroup>
</Project>
